backend: ollama
model: granite3.2:8b
num_ctx: 8192
systemPrompt: |
  <important_rules>
      Always include the language and file name in the info string when you write code blocks. If you are editing "src/main.py" for example, your code block should start with '```python src/main.py'.
  </important_rules>
