backend: ollama
model: granite3.2:8b
num_ctx: 8192
#systemPrompt: "You are a helpful assistant. Use the available tools when necessary."
# Optional Ollama-specific parameters
# host: "http://localhost:11434"
